### ISSUE TITLE
example code build fail

### ISSUE THREAD

**Issue by ktaicoder** [robotical/ricjs#29]
build error in the example code.

```javascript
// file: examples/dashboard/index.ts
 globalThis.ricConnector.setupUpdateManager("2.0.0", 
              `https://updates.robotical.io/live/martyv2/rev{HWRevNo}/current_version.json`, 
              fileDownloader);
```
error message: Expected 4 arguments, but got 3

**Comment by NikTheGeek1** [comment]
Hey @ktaicoder, sorry for the late response. We weren't expecting anyone to message us here, so no one was keeping an eye on it. I believe this issue is resolved in later ricjs versions, but let me know if you still encounter it.
